export const ReportTranslation = [
  {
    key: 'docTitle',
    en: 'Integrated SDG Insights',
    fr: 'Perspectives intégrées sur les ODD',
    es: 'Perspectivas integradas de los ODS',
    ru: 'Интегрированные понимания ЦРУ',
  },
  {
    key: 'poweredBy',
    en: 'Powered by',
    fr: 'Propulsé par le',
    es: 'Impulsado por el',
    ru: 'Разработано',
  },
  {
    key: 'summaryReport',
    en: 'Summary Report',
    fr: 'Rapport sommaire',
    es: 'Informe resumido',
    ru: 'Сводный отчет',
  },
  {
    key: 'reportGenerated',
    en: 'This report has been generated through the',
    fr: 'Ce rapport a été généré grâce à',
    es: 'Este informe ha sido generado a través de',
    ru: 'Этот отчет был сгенерирован с помощью',
  },
  {
    key: 'for',
    en: 'for',
    fr: 'pour',
    es: 'para',
    ru: 'для',
  },
  {
    key: 'on',
    en: 'on',
    fr: 'sur',
    es: 'sobre',
    ru: 'на',
  },
  {
    key: 'background',
    en: 'Background',
    fr: 'Contexte',
    es: 'Antecedentes',
    ru: 'Контекст',
  },
  {
    key: 'docIntro',
    en: 'The SDG Push Diagnostic helps countries practically advance transformative pathways. It integrates multiple data sources and digital innovation to establish a rapid landscape analysis – national priorities, current trends, potential futures, and interlinkages.',
    fr: 'Le Diagnostic "SDG Push" aide les pays à avancer concrètement sur les voies de transformation. Il intègre plusieurs sources de données et des innovations numériques pour établir une analyse rapide du paysage - priorités nationales, tendances actuelles, futurs potentiels et interconnexions.',
    es: 'El Diagnóstico "SDG Push" ayuda a los países a avanzar prácticamente en vías transformadoras. Integra múltiples fuentes de datos e innovación digital para establecer un análisis rápido del panorama: prioridades nacionales, tendencias actuales, futuros potenciales e interconexiones.',
    ru: 'Диагностика "SDG Push" помогает странам практически продвигаться по трансформационным путям. Она интегрирует несколько источников данных и цифровых инноваций для быстрого анализа ландшафта - национальных приоритетов, текущих тенденций, потенциальных будущих сценариев и взаимосвязей.',
  },
  {
    key: 'sdgPushIntro',
    en: 'The SDG Push Diagnostic is the foundation for a tailored ‘Integrated SDG Insights’ report that helps member states assess areas where they are making investments with biggest multiplier effects, and chart transformative pathways as part of their national commitments at the SDG Summit.',
    fr: 'Le Diagnostic de stimulation des ODD sert de base à un rapport sur les « Perspectives intégrées sur les ODD » sur mesure qui aide les États membres à évaluer les domaines dans lesquels ils investissent pour obtenir les plus grands effets multiplicateurs et à tracer des voies de transformation dans le cadre de leurs engagements nationaux au Sommet des ODD.',
    es: 'El diagnóstico del impulso de los ODS es la base de un informe personalizado de "Perspectivas integradas sobre los ODS" que ayuda a los Estados miembros a evaluar las áreas en las que están invirtiendo con los mayores efectos multiplicadores, y trazar caminos transformadores como parte de sus compromisos nacionales en la Cumbre de los ODS.',
    ru: 'Диагностика содействия ЦРУ является основой для индивидуального отчета «Интегрированные понимания ЦРУ», который помогает государствам-участникам оценить области, в которых они инвестируют с наибольшими множителями эффектов, и наметить трансформационные пути в рамках их национальных обязательств на саммите ЦРУ.',
  },
  {
    key: 'currentPriorities',
    en: 'Current Priorities',
    fr: 'Priorités actuelles',
    es: 'Prioridades actuales',
    ru: 'Текущие приоритеты',
  },
  {
    key: 'priorityAnalysis',
    en: 'This section analyzes national SDG priorities based on key national documents such as national development plans, Voluntary National Reviews (VNRs) and any other relevant policy documents outlining government development priorities. This text analysis provides a summarized review of lengthy policy documents and maps them to the SDGs. The output reveals the most prominent SDGs that are mentioned across key policy documents.',
    fr: "Cette section analyse les priorités nationales en matière d'ODD à partir de documents clés tels que les plans nationaux de développement, les examens nationaux volontaires (ENV) et tout autre document de politique pertinent décrivant les priorités de développement du gouvernement. Cette analyse textuelle fournit une revue résumée des documents de politique longs et les cartographie aux ODD. Les résultats révèlent les ODD les plus fréquemment mentionnés dans les documents de politique clés.",
    es: 'Esta sección analiza las prioridades nacionales de los ODS basándose en documentos nacionales clave, como planes nacionales de desarrollo, Revisiones Nacionales Voluntarias (RNV) y cualquier otro documento de política relevante que describa las prioridades de desarrollo del gobierno. Este análisis de texto proporciona una revisión resumida de los documentos de política largos y los relaciona con los ODS. La salida revela los ODS más prominentes que se mencionan en los documentos de política clave.',
    ru: 'Этот раздел анализирует приоритеты страны в области ЦРУ на основе ключевых национальных документов, таких как национальные планы развития, Добровольные Национальные Обзоры (ДНО) и любые другие соответствующие политические документы, описывающие приоритеты развития правительства. Этот текстовый анализ обеспечивает краткое обзор политических документов и картографирует их на ЦРУ. Результаты показывают наиболее выделяющиеся ЦРУ, упоминаемые в ключевых политических документах.',
  },
  {
    key: 'sdgAnalysisMethodology',
    en: 'The analysis is generated using machine learning text analysis to surface priorities that can be mapped to the SDGs. The model analyzes the document by linking its constituent pieces to SDGs and then aggregates the statistics before presenting the results. The underlying assumption of the analysis is that the amount of text linked to each SDG defines how important each SDG is. In this context, the “importance” of an SDG is referred to as “salience”. Thus, the most salient SDG is the one to which most of the text pieces, e.g., paragraphs, could be linked. Refer to the',
    fr: "L'analyse est générée à l'aide de l'analyse de texte basée sur l'apprentissage automatique pour mettre en évidence les priorités qui peuvent être associées aux ODD. Le modèle analyse le document en liant ses éléments constitutifs aux ODD, puis agrège les statistiques avant de présenter les résultats. L'hypothèse sous-jacente de l'analyse est que la quantité de texte liée à chaque ODD définit l'importance de chaque ODD. Dans ce contexte, l'« importance » d'un ODD est appelée « saillance ». Ainsi, l'ODD le plus saillant est celui auquel la plupart des éléments de texte, par exemple des paragraphes, peuvent être liés. Veuillez vous référer au",
    es: 'El análisis se genera mediante el análisis de texto de aprendizaje automático para identificar las prioridades que se pueden asignar a los ODS. El modelo analiza el documento vinculando sus elementos constituyentes a los ODS y luego agrega las estadísticas antes de presentar los resultados. El supuesto subyacente del análisis es que la cantidad de texto vinculado a cada ODS define la importancia de cada ODS. En este contexto, la "importancia" de un ODS se denomina "salencia". Por lo tanto, el ODS más saliente es aquel al que se pueden vincular la mayoría de los elementos de texto, como párrafos. Consulte la',
    ru: 'Анализ генерируется с использованием анализа текста с применением машинного обучения для выявления приоритетов, которые можно отобразить на ЦРУ. Модель анализирует документ, связывая его составные части с ЦРУ, а затем агрегирует статистические данные перед представлением результатов. Основное предположение анализа состоит в том, что количество текста, связанного с каждым ЦРУ, определяет, насколько важен каждый ЦРУ. В этом контексте',
  },
  {
    key: 'detailedMethodology',
    en: 'for a detailed methodology.',
    fr: 'pour une méthodologie détaillée.',
    es: 'para obtener una metodología detallada.',
    ru: 'для подробной методологии.',
  },
  {
    key: 'countryActionPriorities',
    en: 'For {{countryName}}, analyzing the major priorities in the current action documents by the country, we find {{sdgList}} are likely high priority.',
    fr: "Pour {{countryName}}, en analysant les principales priorités dans les documents d'action actuels du pays, nous constatons que les {{sdgList}} sont probablement des priorités élevées.",
    es: 'Para {{countryName}}, al analizar las principales prioridades en los documentos de acción actuales del país, encontramos que {{sdgList}} son probablemente de alta prioridad.',
    ru: 'Для {{countryName}}, анализируя основные приоритеты в текущих документах действий страны, мы находим, что {{sdList}} вероятно, высокий приоритет.',
  },
  {
    key: 'detailedMethodologyPara1',
    en: 'The output from the text analysis is overlayed with the SDG ‘status’, to map which SDGs are off-track in reaching the 2030 goals. This comparison is important in pointing out the gaps and opportunities of the current national SDG policy priorities versus how the SDGs are performing on the ground. The comparison can guide potential opportunities for SDG investments in optimizing national priorities and achieving the sustainable development goals.',
    fr: "La sortie de l'analyse de texte est superposée à l'état des ODD pour cartographier les ODD qui sont en dehors de la voie pour atteindre les objectifs de 2030. Cette comparaison est importante pour souligner les lacunes et les opportunités des priorités nationales actuelles en matière de politiques de développement durable par rapport à la façon dont les ODD se comportent sur le terrain. Cette comparaison peut orienter les opportunités potentielles d'investissement dans les ODD pour optimiser les priorités nationales et atteindre les objectifs de développement durable.",
    es: 'La salida del análisis de texto se superpone con el "estatus" de los ODS para mapear qué ODS están fuera de curso en la consecución de los objetivos de 2030. Esta comparación es importante para señalar las brechas y oportunidades de las actuales prioridades de política nacional de ODS frente a cómo se desempeñan los ODS en el terreno. La comparación puede guiar oportunidades potenciales de inversión en ODS para optimizar las prioridades nacionales y lograr los objetivos de desarrollo sostenible.',
    ru: 'Результат анализа текста наложен на "статус" ЦРУ, чтобы отобразить, какие ЦРУ не соответствуют целям на 2030 год. Это сравнение важно для выявления пробелов и возможностей текущих национальных приоритетов политики ЦРУ по сравнению с тем, как ЦРУ выполняются на местах. Сравнение может указать на потенциальные возможности инвестирования в ЦРУ для оптимизации национальных приоритетов и достижения целей устойчивого развития.',
  },
  {
    key: 'MatrixMapping',
    en: 'The matrix below maps national priorities and current trends. This can provide meaningful insights for national dialogues and identification of transformative pathways.',
    fr: 'La matrice ci-dessous cartographie les priorités nationales et les tendances actuelles. Cela peut fournir des informations significatives pour les dialogues nationaux et l’identification de voies de transformation.',
    es: 'La matriz a continuación mapea las prioridades nacionales y las tendencias actuales. Esto puede proporcionar información significativa para los diálogos nacionales y la identificación de trayectorias transformadoras.',
    ru: 'Матрица ниже отображает национальные приоритеты и текущие тенденции. Это может предоставить значимые идеи для национального диалога и определения пути преобразования.',
  },
  {
    key: 'comparingSDGNationalPriorities',
    en: 'Comparing SDG national priorities based on {{docName}} and SDG gaps',
    fr: "Comparaison des priorités nationales en matière d'ODD en fonction des {{docName}} et des écarts des ODD",
    es: 'Comparación de las prioridades nacionales de los ODS basada en {{docName}} y brechas en los ODS',
    ru: 'Сравнение национальных приоритетов ЦРУ на основе {{docName}} и разрывов ЦРУ',
  },
  {
    key: 'SDGMatrixParameters',
    en: 'This matrix maps the SDGs along two parameters: ',
    fr: 'Cette matrice cartographie les ODD selon deux paramètres : ',
    es: 'Esta matriz mapea los ODS a lo largo de dos parámetros: ',
    ru: 'Эта матрица отображает ЦРУ по двум параметрам: ',
  },
  {
    key: 'SDGMatrixParametersPoint1',
    en: 'their current trend status and ',
    fr: 'leur statut de tendance actuelle et ',
    es: 'su estado de tendencia actual y ',
    ru: 'их текущий статус тенденций и ',
  },
  {
    key: 'SDGMatrixParametersPoint2',
    en: 'their priority status as identified in {{docName}}.',
    fr: "leur statut de priorité tel qu'identifié dans le {{docName}}.",
    es: 'su estado de prioridad según se identifica en el {{docName}}.',
    ru: 'их статус приоритета, определенный в {{docName}}.',
  },
  {
    key: 'disclaimer',
    en: 'Disclaimer: The current priorities identified may not reflect the actual and complete priorities of the government. They are a starting point for further discussion.',
    fr: 'Avertissement: Les priorités actuelles identifiées peuvent ne pas refléter les priorités réelles et complètes du gouvernement. Elles sont un point de départ pour une discussion ultérieure.',
    es: 'Descargo de responsabilidad: Las prioridades actuales identificadas pueden no reflejar las prioridades reales y completas del gobierno. Son un punto de partida para una discusión posterior.',
    ru: 'Отказ от ответственности: Текущие приоритеты, выявленные могут не отражать фактические и полные приоритеты правительства. Они являются отправной точкой для дальнейшего обсуждения.',
  },
  {
    key: 'currentTrends',
    en: 'Current Trends',
    fr: 'Tendances actuelles',
    es: 'Tendencias actuales',
    ru: 'Текущие тенденции',
  },
  {
    key: 'currentTrendsIntro',
    en: "The 'Current Trends' measures the progress of the SDGs. Progress on the 17 SDGs are tracked through 169 sub-targets, which in turn are measured using 231 unique indicators. This analysis provides a categorization and overview of the SDGs and corresponding targets and indicators which are on-track or off-track at the national level, providing the baseline landscape against which to build the SDG Push.",
    fr: "'Tendances actuelles' mesure les progrès des ODD. Les progrès des 17 ODD sont suivis à travers 169 sous-objectifs, qui sont mesurés à leur tour à l'aide de 231 indicateurs uniques. Cette analyse fournit une catégorisation et une vue d'ensemble des ODD et des objectifs et indicateurs correspondants qui sont sur la bonne voie ou hors de la voie à l'échelle nationale, fournissant le paysage de base sur lequel construire la SDG Push.",
    es: 'La sección "Tendencias actuales" mide el progreso de los ODS. El progreso en los 17 ODS se realiza mediante el seguimiento de 169 subobjetivos, que a su vez se miden utilizando 231 indicadores únicos. Este análisis proporciona una categorización y una descripción general de los ODS y los objetivos e indicadores correspondientes que están en la buena dirección o fuera de la buena dirección a nivel nacional, proporcionando el paisaje de referencia sobre el que construir el impulso de los ODS.',
    ru: '«Текущие тенденции» отображают прогресс достижения ЦРУ. Прогресс по 17 ЦРУ отслеживается через 169 подцелей, которые в свою очередь измеряются с помощью 231 уникального показателя. Этот анализ обеспечивает категоризацию и обзор ЦРУ, а также соответствующих целей и показателей, которые достигаются или не достигаются на национальном уровне, предоставляя базовый ландшафт, на котором можно построить SDG Push.',
  },
  {
    key: 'sdg',
    en: 'SDG',
    fr: 'ODD',
    es: 'ODS',
    ru: 'ЦРУ',
  },
  {
    key: 'outOf',
    en: ', out of 17 SDGs, ',
    fr: ', sur les 17 ODD, ',
    es: ', de los 17 ODS, ',
    ru: ', из 17 ЦРП, ',
  },
  {
    key: 'are',
    en: 'are',
    fr: 'sont',
    es: 'están',
    ru: 'находится',
  },
  {
    key: 'is',
    en: 'is',
    fr: 'est',
    es: 'está',
    ru: 'находится',
  },
  {
    key: 'sdgInterlinkages',
    en: 'SDG Interlinkages',
    fr: 'Interconnexions des ODD',
    es: 'Interconexiones de los ODS',
    ru: ' Взаимосвязи ЦУР',
  },
  {
    key: 'interlinkagesPara1',
    en: 'The SDGs do not exist in silos, understanding how the goals are interconnected, both positively and negatively, is essential to understanding the mechanisms for achieving the targets. A better understanding of patterns of synergies and trade-offs can support strategic decision making and promote game-changing interventions for the SDGs.',
    fr: "Les ODD ne sont pas cloisonnés, comprendre comment les objectifs sont interconnectés, à la fois positivement et négativement, est essentiel pour comprendre les mécanismes permettant d'atteindre les cibles. Une meilleure compréhension des modèles de synergies et de compromis peut soutenir la prise de décisions stratégiques et favoriser des interventions décisives pour les ODD.",
    es: 'Los ODS no existen en silos, comprender cómo los objetivos están interconectados, tanto positiva como negativamente, es esencial para comprender los mecanismos para lograr las metas. Una mejor comprensión de los patrones de sinergias y compensaciones puede apoyar la toma de decisiones estratégicas y promover intervenciones innovadoras para los ODS.',
    ru: 'ЦУР не существуют в отдельных сферах, понимание того, как цели взаимосвязаны, как в позитивном, так и в негативном аспектах, является важным для понимания механизмов достижения целей. Лучшее понимание паттернов синергий и компромиссов может поддерживать стратегическое принятие решений и способствовать революционным интервенциям для ЦУР.',
  },
  {
    key: 'interlinkagesPara2',
    en: 'This section considers the interlinkages between SDGs and their targets. It considers the national priorities and their SDG ‘status’ and investigates which SDG targets has the most synergies and hence potential for a positive multiplier effect on other SDG targets.',
    fr: "Cette section examine les interconnexions entre les ODD et leurs cibles. Elle examine les priorités nationales et leur « statut » ODD et étudie les cibles des ODD qui ont le plus de synergies et donc le potentiel d'avoir un effet multiplicateur positif sur d'autres cibles des ODD.",
    es: "Esta sección considera las interconexiones entre los ODS y sus metas. Considera las prioridades nacionales y su 'estatus' ODS e investiga cuáles metas de los ODS tienen más sinergias y, por lo tanto, un mayor potencial para un efecto multiplicador positivo en otras metas de los ODS.",
    ru: "Этот раздел рассматривает взаимосвязи между ЦУР и их целями. Он рассматривает национальные приоритеты и их 'статус' ЦУР и исследует, какие цели ЦУР имеют наибольшую синергию и, следовательно, потенциал для положительного множителя на другие цели ЦУР.",
  },
  {
    key: 'interlinkagesBoxPara1',
    en: 'For {{countryName}}, SDG {{sdgNo}} has been identified as having {{status}} as well as being high priority as per the documents uploaded.',
    fr: "Pour {{countryName}}, l'ODD {{sdgNo}} a été identifié comme ayant {{status}} et étant une priorité élevée selon les documents téléchargés.",
    es: 'Para {{countryName}}, se ha identificado que el ODS {{sdgNo}} tiene {{status}} y es de alta prioridad según los documentos cargados.',
    ru: 'Для {{countryName}} ЦУР {{sdgNo}} был определен как имеющий {{status}}, а также являющийся высоким приоритетом согласно загруженным документам.',
  },
  {
    key: 'interlinkagesBoxPara2',
    en: 'Within SDG {{sdgNo}}, Target {{targetNo}} has the highest potential for a positive multiplier effect as it’s connected with the most targets across the SDG.',
    fr: "Au sein de l'ODD {{sdgNo}}, la cible {{targetNo}} a le plus grand potentiel d'effet multiplicateur positif car elle est connectée à la plupart des cibles de l'ODD.",
    es: 'Dentro del ODS {{sdgNo}}, el Objetivo {{targetNo}} tiene el mayor potencial para un efecto multiplicador positivo ya que está conectado con la mayoría de las metas en todo el ODS.',
    ru: 'Цель {{targetNo}} в составе ЦУР {{sdgNo}} имеет наибольший потенциал для положительного множителя, так как она связана с наибольшим количеством целей по всему ЦУР.',
  },
  {
    key: 'futureScenarios',
    en: 'Future Scenarios',
    fr: 'Scénarios Futurs',
    es: 'Escenarios Futuros',
    ru: 'Будущие Сценарии',
  },
  {
    key: 'futureScenariosPara1',
    en: 'Based on International Futures model developed by the Pardee Center for International Futures at the University of Denver the analysis presents the impact of different scenarios of three different scenarios on the SDGs. While COVID-19 can lead to severe long-term impacts, a set of ambitious but feasible integrated SDG investments in governance, social protection, digital and green recovery can help countries see what could be possible to narrow the gaps and revert negative trends.',
    fr: "Basée sur le modèle International Futures développé par le Pardee Center for International Futures de l'Université de Denver, l'analyse présente l'impact de trois scénarios différents sur les ODD. Bien que la COVID-19 puisse avoir des impacts graves à long terme, un ensemble d'investissements ambitieux mais réalisables dans la gouvernance, la protection sociale, la récupération numérique et verte peut aider les pays à voir ce qui est possible pour réduire les écarts et inverser les tendances négatives.",
    es: 'Basado en el modelo International Futures desarrollado por el Pardee Center for International Futures en la Universidad de Denver, el análisis presenta el impacto de diferentes escenarios en los ODS. Si bien COVID-19 puede tener graves impactos a largo plazo, un conjunto ambicioso pero factible de inversiones integradas en los ODS en gobernanza, protección social, recuperación digital y verde puede ayudar a los países a ver lo que podría ser posible para reducir las brechas y revertir las tendencias negativas.',
    ru: 'На основе модели International Futures, разработанной Парди Центром международного будущего при Университете Денвера, анализ представляет влияние трех различных сценариев на ЦУР. Хотя COVID-19 может привести к серьезным долгосрочным последствиям, набор амбициозных, но осуществимых инвестиций в ЦУР в области управления, социальной защиты, цифровой и зеленой реконструкции может помочь странам увидеть, что может быть возможным для сужения разрывов и изменения негативных тенденций.',
  },
  {
    key: 'futureScenariosPara2',
    en: 'These SDG Investments, detailed below, are aimed at narrowing the gaps identified in the ‘Current SDG Gaps’ page. Their projected impact over the coming decades is visualized here as the “SDG Push” scenario.',
    fr: "Ces investissements dans les ODD, détaillés ci-dessous, visent à réduire les écarts identifiés dans la page 'Écarts actuels dans les ODD'. Leur impact prévu au cours des prochaines décennies est visualisé ici sous le scénario « SDG Push ».",
    es: "Estas inversiones en los ODS, detalladas a continuación, tienen como objetivo reducir las brechas identificadas en la página 'Brechas actuales en los ODS'. Su impacto proyectado en las próximas décadas se visualiza aquí como el escenario 'SDG Push'.",
    ru: "Эти инвестиции в ЦУР, описанные ниже, направлены на сужение выявленных разрывов в 'Текущих разрывах ЦУР'. Их прогнозируемый эффект на протяжении предстоящих десятилетий визуализируется здесь как сценарий 'SDG Push'.",
  },
  {
    key: 'futureScenariosPara3',
    en: 'The SDG Push (governance, social protection, digital, green recovery) and SDG Push Plus (achieving universal electricity access) present analysis of potential for addressing the “grand challenges” awaiting global community and countries. It helps a country see what could be possible, as a point for reflection using a systems model.',
    fr: "Les initiatives SDG Push (gouvernance, protection sociale, numérique, relance verte) et SDG Push Plus (accès universel à l'électricité) présentent une analyse du potentiel pour relever les « grands défis » auxquels la communauté mondiale et les pays sont confrontés. Cela aide un pays à voir ce qui est possible, en tant que point de réflexion à l'aide d'un modèle systémique.",
    es: "Las iniciativas SDG Push (gobernanza, protección social, digital, recuperación verde) y SDG Push Plus (lograr el acceso universal a la electricidad) presentan un análisis del potencial para abordar los 'grandes desafíos' que esperan a la comunidad global y a los países. Ayuda a un país a ver lo que podría ser posible, como punto de reflexión utilizando un modelo de sistemas.",
    ru: 'Инициативы SDG Push (управление, социальная защита, цифровые технологии, зеленое восстановление) и SDG Push Plus (достижение универсального доступа к электричеству) представляют анализ потенциала для решения «больших вызовов», ожидающих глобальное сообщество и страны. Это помогает стране увидеть, что может быть возможным, как точку отражения, используя системную модель.',
  },
  {
    key: 'futureScenariosPara4Part1',
    en: 'This analysis is based ',
    fr: 'Cette analyse est basée sur ',
    es: 'Este análisis se basa en ',
    ru: 'Этот анализ основан на ',
  },
  {
    key: 'futureScenariosPara4Part2',
    en: "UNDP's flagship study",
    fr: "l'étude phare du PNUD",
    es: 'el estudio emblemático del PNUD, realizado con el Centro Pardee para Futuros Internacionales de la Universidad de Denver. Se basa en el modelo International Futures (IFs) utilizado para proyectar las tendencias de desarrollo en diferentes metas de los ODS y los efectos de un conjunto combinado de intervenciones en las áreas de Gobernanza, Protección Social, Economía Verde y Disrupción Digital a través de diferentes escenarios predefinidos. Debido a la flexibilidad del modelo, se puede utilizar para proporcionar intervenciones políticas específicas para abordar las prioridades específicas del país teniendo en cuenta las dinámicas dentro y entre los sistemas globales.',
    ru: 'флагманском исследовании ПРООН',
  },
  {
    key: 'futureScenariosPara4Part3',
    en: ', conducted with the Pardee Center for international Futures at the University of Denver. It is based on the International Futures (IFs) model used to project the development trends across different SDG targets and the effects of combined set of interventions in the areas of Governance, Social Protection, Green Economy, and Digital Disruption across different and predefined set of scenarios. Because of model’s flexibility it may be used to provide targeted policy interventions to tackle country specific priorities keeping in mind dynamics within and across global systems.',
    fr: ", menée avec le Pardee Center pour l'avenir international de l'Université de Denver. Elle repose sur le modèle International Futures (IFs) utilisé pour projeter les tendances de développement dans différents objectifs de développement durable (ODD) et les effets d'un ensemble combiné d'interventions dans les domaines de la gouvernance, de la protection sociale, de l'économie verte et de la perturbation numérique à travers différents scénarios prédéfinis. En raison de la flexibilité du modèle, il peut être utilisé pour fournir des interventions politiques ciblées pour s'attaquer aux priorités spécifiques des pays en gardant à l'esprit les dynamiques au sein et entre les systèmes mondiaux.",
    es: ', realizado con el Centro Pardee para Futuros Internacionales de la Universidad de Denver. Se basa en el modelo International Futures (IFs) utilizado para proyectar las tendencias de desarrollo en diferentes metas de los ODS y los efectos de un conjunto combinado de intervenciones en las áreas de Gobernanza, Protección Social, Economía Verde y Disrupción Digital a través de diferentes escenarios predefinidos. Debido a la flexibilidad del modelo, se puede utilizar para proporcionar intervenciones políticas específicas para abordar las prioridades específicas del país teniendo en cuenta las dinámicas dentro y entre los sistemas globales.',
    ru: ', проведенном с Центром Парди для международных будущих исследований в Университете Денвера. Он основан на модели International Futures (IFs), используемой для прогнозирования тенденций развития по различным ЦУР и эффектов комбинированного набора мер в областях управления, социальной защиты, зеленой экономики и цифровой дисрупции в различных заранее определенных сценариях. Благодаря гибкости модели, ее можно использовать для предоставления целенаправленных политических мер, направленных на решение конкретных задач стран, учитывая динамику внутри и между глобальными системами.',
  },
];
