name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - staging

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      VITE_AIAAS_API_BASE_URL: ${{secrets.VITE_AIAAS_API_BASE_URL}}
      VITE_AIAAS_API_KEY: ${{secrets.VITE_AIAAS_API_KEY}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_ISLAND_066846403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          production_branch: "main"
